version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - loki
    networks:
      - monitoring
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - fastapi
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - fastapi  # Ensure Prometheus starts after FastAPI

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"

networks:
  monitoring:
    driver: bridge
