"""New Migration

Revision ID: 0e8b5db24f0f
Revises: 36752c911df2
Create Date: 2024-12-26 00:50:22.696056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8b5db24f0f'
down_revision: Union[str, None] = '36752c911df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('timezone', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'timezone')
    # ### end Alembic commands ###
