"""New Migration

Revision ID: 3af0ad4cfa55
Revises: ebfbc6d65064
Create Date: 2024-12-25 12:23:06.044659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af0ad4cfa55'
down_revision: Union[str, None] = 'ebfbc6d65064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('address', sa.String(), nullable=False))
    op.add_column('leads', sa.Column('zipcode', sa.String(), nullable=False))
    op.add_column('leads', sa.Column('state', sa.String(), nullable=False))
    op.add_column('leads', sa.Column('country', sa.String(), nullable=False))
    op.add_column('leads', sa.Column('area_of_interest', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'area_of_interest')
    op.drop_column('leads', 'country')
    op.drop_column('leads', 'state')
    op.drop_column('leads', 'zipcode')
    op.drop_column('leads', 'address')
    # ### end Alembic commands ###
