"""removed def from lead timezone

Revision ID: 8c903eb1fc9f
Revises: efb08b67f783
Create Date: 2024-12-28 16:58:21.556941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c903eb1fc9f'
down_revision: Union[str, None] = 'efb08b67f783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
