"""New Migration

Revision ID: ca7d55924d79
Revises: c91f36fdeafa
Create Date: 2024-12-28 03:17:11.087957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7d55924d79'
down_revision: Union[str, None] = 'c91f36fdeafa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls_tracking', sa.Column('poc', sa.String(), nullable=True))
    op.create_foreign_key(None, 'calls_tracking', 'point_of_contacts', ['poc'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calls_tracking', type_='foreignkey')
    op.drop_column('calls_tracking', 'poc')
    # ### end Alembic commands ###
