"""New Migration

Revision ID: eacf3ad55b0f
Revises: 
Create Date: 2024-12-24 17:06:00.511157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eacf3ad55b0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls_tracking', sa.Column('frequency', sa.Integer(), nullable=True))
    op.add_column('calls_tracking', sa.Column('last_call_date', sa.DateTime(), nullable=True))
    op.drop_column('calls_tracking', 'details')
    op.drop_column('calls_tracking', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls_tracking', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('calls_tracking', sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('calls_tracking', 'last_call_date')
    op.drop_column('calls_tracking', 'frequency')
    # ### end Alembic commands ###
