"""New Migration

Revision ID: ebfbc6d65064
Revises: eacf3ad55b0f
Create Date: 2024-12-24 21:31:07.911043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfbc6d65064'
down_revision: Union[str, None] = 'eacf3ad55b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls_tracking', sa.Column('next_call_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls_tracking', 'next_call_date')
    # ### end Alembic commands ###
